/**
 * Advanced tab of the settings hub: general behaviour, backup and campus
 * maintenance, the "Lighten the Intra" switches, and Reset.
 */
import { CONFIG_DEFAULT } from "../../../core/config.ts";
import type { HubSettingDef } from "../hubSettings.data.ts";

export const ADVANCED_SETTINGS: readonly HubSettingDef[] = [
  {
    feature: "advanced",
    key: "ADVANCED_OPEN_LINKS_NEW_TAB",
    label: "Open links in new tab",
    desc: "External links from Better Intra open in a new tab instead of the current one.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.ADVANCED_OPEN_LINKS_NEW_TAB,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "advanced",
    key: "EASTER_EGGS_ENABLED",
    label: "Easter eggs",
    desc: "Nine small secrets are hidden in the Intra. The About tab counts the ones you found.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.EASTER_EGGS_ENABLED,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "advanced",
    key: "DISABLE_ANIMATIONS",
    label: "Disable animations",
    desc: "Removes transition effects across all Better Intra features.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.DISABLE_ANIMATIONS,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "advanced",
    label: "Auto-detected campus",
    desc: "Your campus, detected automatically via the 42 API.",
    kind: "campus-info",
    fullWidth: false,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "advanced",
    label: "Backup & Restore",
    desc: "Export or import your Better Intra settings as a JSON file.",
    kind: "action",
    actionType: "backup",
    actionLabel: "Backup",
    grid: true,
    colSpan: 1,
  },
  {
    feature: "advanced",
    label: "Reload campus config",
    desc: "Clears the cached campus/cluster configuration and re-fetches it.",
    kind: "action",
    actionType: "reload-campus",
    actionLabel: "Reload",
    grid: true,
    colSpan: 1,
  },
  { feature: "advanced", label: "Lighten the Intra", kind: "divider" },
  {
    feature: "advanced",
    key: "PERF_DEFER_OFFSCREEN",
    label: "Skip off-screen blocks",
    desc: "The browser stops laying out and painting the project rows, achievement tiles, evaluation rows and logtime months you have scrolled past. Long lists get much smoother. Costs: a block is drawn the moment it reaches the screen, so a very fast scroll can flash blank for a frame.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PERF_DEFER_OFFSCREEN,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "advanced",
    key: "PERF_LAZY_IMAGES",
    label: "Load images when needed",
    desc: "Avatars and icons far below the fold are only downloaded and decoded once you scroll to them, instead of all at once on load. Costs: an image can appear a moment after you reach it on a slow connection. Never applied to Better Intra's own widgets.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PERF_LAZY_IMAGES,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "advanced",
    key: "PERF_PAUSE_HIDDEN",
    label: "Pause when tab is hidden",
    desc: "While this tab is in the background, the Intra's animations and transitions are paused, so it stops using your CPU and battery. Costs: nothing visible - everything resumes the instant you come back.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PERF_PAUSE_HIDDEN,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "advanced",
    key: "PERF_PRECONNECT",
    label: "Warm up the avatar CDN",
    desc: "Opens the connection to cdn.intra.42.fr as the page starts, so the first avatar does not wait for DNS and the TLS handshake. Costs: three empty <link> tags and one early connection.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PERF_PRECONNECT,
    grid: true,
    colSpan: 1,
  },

  { feature: "advanced", label: "Reset", kind: "divider" },
  {
    feature: "advanced",
    label: "Reset all data",
    desc: "Clear all Better Intra settings and start fresh. This cannot be undone.",
    kind: "action",
    actionType: "reset",
    actionLabel: "Reset",
  },
];
