/**
 * Customize tab of the settings hub: presets and sharing, accent, palette,
 * background, cards, layout, typography and custom CSS, applied on every
 * Intra page by src/features/customize/.
 */
import { CONFIG_DEFAULT } from "../../../core/config.ts";
import type { HubSettingDef } from "../hubSettings.data.ts";
import { BG_PRESET_OPTIONS } from "./options.ts";

export const CUSTOMIZE_SETTINGS: readonly HubSettingDef[] = [
  {
    feature: "customize",
    label: "Presets & sharing",
    desc: "Save your look under a name, switch between presets, and share a theme code with friends.",
    kind: "custom-presets",
    fullWidth: true,
  },
  { feature: "customize", label: "Show your look to others", kind: "divider" },
  {
    feature: "customize",
    key: "CUSTOM_SHARE_LOOK",
    label: "Publish my look on my profile",
    desc: "Other Better Intra users see your accent, palette, background and card style when they open your profile. Fonts, size, scrollbar and custom CSS are never shared. Needs the cloud account.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.CUSTOM_SHARE_LOOK,
    requiresCloud: true,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_SHOW_OTHERS_LOOK",
    label: "Show other people's looks",
    desc: "Apply the look a student published when you visit their profile. Turn off to always keep your own style.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.CUSTOM_SHOW_OTHERS_LOOK,
    grid: true,
    colSpan: 1,
  },
  { feature: "customize", label: "Accent", kind: "divider" },
  {
    feature: "customize",
    key: "CUSTOM_ACCENT_ENABLED",
    label: "Custom accent colour",
    desc: "Use your own colour instead of the theme preset's accent.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.CUSTOM_ACCENT_ENABLED,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_ACCENT_COLOR",
    label: "Accent colour",
    desc: "Buttons, links, highlights and progress bars across the intranet.",
    kind: "color",
    placeholder: "#00babc",
    defaultValue: CONFIG_DEFAULT.CUSTOM_ACCENT_COLOR,
    dependsOn: "CUSTOM_ACCENT_ENABLED",
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_ACCENT_GRADIENT",
    label: "Two-colour accent",
    desc: "Buttons and progress bars fade from the accent colour to a second one.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.CUSTOM_ACCENT_GRADIENT,
    dependsOn: "CUSTOM_ACCENT_ENABLED",
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_ACCENT_COLOR_2",
    label: "Second colour",
    desc: "End colour of the accent gradient.",
    kind: "color",
    placeholder: "#7c3aed",
    defaultValue: CONFIG_DEFAULT.CUSTOM_ACCENT_COLOR_2,
    dependsOn: "CUSTOM_ACCENT_GRADIENT",
    grid: true,
    colSpan: 1,
  },
  { feature: "customize", label: "Colours", kind: "divider" },
  {
    feature: "customize",
    key: "CUSTOM_THEME_ENABLED",
    label: "Custom palette",
    desc: "Replace the theme's page, card and text colours with your own. Works best with the dark theme.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.CUSTOM_THEME_ENABLED,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_THEME_BG",
    label: "Page colour",
    desc: "Background of the pages.",
    kind: "color",
    placeholder: "#1c2130",
    defaultValue: CONFIG_DEFAULT.CUSTOM_THEME_BG,
    dependsOn: "CUSTOM_THEME_ENABLED",
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_THEME_CARD",
    label: "Card colour",
    desc: "Cards, sidebar, popovers and inputs.",
    kind: "color",
    placeholder: "#151a24",
    defaultValue: CONFIG_DEFAULT.CUSTOM_THEME_CARD,
    dependsOn: "CUSTOM_THEME_ENABLED",
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_THEME_TEXT",
    label: "Text colour",
    desc: "Main text colour; secondary text is derived from it.",
    kind: "color",
    placeholder: "#e2e8f0",
    defaultValue: CONFIG_DEFAULT.CUSTOM_THEME_TEXT,
    dependsOn: "CUSTOM_THEME_ENABLED",
    grid: true,
    colSpan: 1,
  },
  { feature: "customize", label: "Background", kind: "divider" },
  {
    feature: "customize",
    key: "CUSTOM_PAGE_BG_URL",
    label: "Page background image",
    desc: "Image URL shown behind every Intra page (fixed, covers the window). Leave empty to disable.",
    kind: "url",
    placeholder: "https://…/wallpaper.jpg",
    defaultValue: CONFIG_DEFAULT.CUSTOM_PAGE_BG_URL,
    fullWidth: true,
  },
  {
    feature: "customize",
    key: "CUSTOM_PAGE_BG_PRESET",
    label: "Background preset",
    desc: "Built-in gradient behind every page, used when no image URL is set.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_PAGE_BG_PRESET,
    options: BG_PRESET_OPTIONS,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_BG_ANIMATE",
    label: "Animate the gradient",
    desc: "Slow drift of the background preset. Off when your system asks for reduced motion.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.CUSTOM_BG_ANIMATE,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_PAGE_BG_DIM",
    label: "Darken image (%)",
    desc: "Dark overlay on the background image to keep text readable. 0–90.",
    kind: "number",
    min: 0,
    max: 90,
    step: 5,
    defaultValue: CONFIG_DEFAULT.CUSTOM_PAGE_BG_DIM,
    dependsOn: "CUSTOM_PAGE_BG_URL",
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_CARD_OPACITY",
    label: "Card opacity (%)",
    desc: "Transparency of cards, with a subtle blur. 30–100.",
    kind: "number",
    min: 30,
    max: 100,
    step: 5,
    defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_OPACITY,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_CARD_STYLE",
    label: "Card style",
    desc: "Shadow and border of cards.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_STYLE,
    options: [
      { label: "Intra default", value: "default" },
      { label: "Flat", value: "flat" },
      { label: "Soft shadow", value: "soft" },
      { label: "Strong shadow", value: "strong" },
      { label: "Outlined (accent)", value: "outlined" },
      { label: "Glass", value: "glass" },
      { label: "Accent stripe", value: "stripe" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_SCROLLBAR",
    label: "Scrollbar",
    desc: "Style of the page scrollbars.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_SCROLLBAR,
    options: [
      { label: "Browser default", value: "default" },
      { label: "Thin", value: "thin" },
      { label: "Thin, accent colour", value: "accent" },
      { label: "Hidden", value: "hidden" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_AVATAR_SHAPE",
    label: "Avatar shape",
    desc: "Shape of the profile picture on profiles.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_AVATAR_SHAPE,
    options: [
      { label: "Circle", value: "circle" },
      { label: "Rounded square", value: "rounded" },
      { label: "Square", value: "square" },
    ],
    grid: true,
    colSpan: 1,
  },
  { feature: "customize", label: "Dashboard cards", kind: "divider" },
  {
    feature: "customize",
    key: "CUSTOM_CARD_BORDER_MODE",
    label: "Card border",
    desc: "Frame every dashboard card (Agenda, Evaluations, Achievements, Projects, Roulette, Logtime) like the Logtime widget.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_BORDER_MODE,
    options: [
      { label: "None", value: "none" },
      { label: "Accent colour", value: "accent" },
      { label: "Custom colour", value: "custom" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_CARD_BORDER_COLOR",
    label: "Border colour",
    desc: "Used when Card border is set to Custom colour.",
    kind: "color",
    placeholder: "#00babc",
    defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_BORDER_COLOR,
    dependsOn: "CUSTOM_CARD_BORDER_MODE",
    dependsOnValues: ["custom"],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_CARD_BORDER_WIDTH",
    label: "Border width (px)",
    desc: "1–6 px, also for per-card borders below.",
    kind: "number",
    min: 1,
    max: 6,
    step: 1,
    defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_BORDER_WIDTH,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_CARD_GLOW",
    label: "Card glow",
    desc: "Soft halo around every card, in the border colour (or the accent).",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_GLOW,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_CARD_TITLE_MODE",
    label: "Card titles",
    desc: "Colour of the AGENDA, PROJECTS… headings.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_TITLE_MODE,
    options: [
      { label: "Intra default", value: "default" },
      { label: "Accent colour", value: "accent" },
      { label: "Custom colour", value: "custom" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_CARD_TITLE_COLOR",
    label: "Title colour",
    desc: "Used when Card titles is set to Custom colour.",
    kind: "color",
    placeholder: "#00babc",
    defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_TITLE_COLOR,
    dependsOn: "CUSTOM_CARD_TITLE_MODE",
    dependsOnValues: ["custom"],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    label: "Per-card colours",
    desc: "Give each card its own background, border and title colour, and a glow. Shared with your public look.",
    kind: "custom-cards",
    fullWidth: true,
  },
  { feature: "customize", label: "Layout", kind: "divider" },
  {
    feature: "customize",
    key: "CUSTOM_DENSITY",
    label: "Density",
    desc: "Spacing between and inside cards. Experimental: follows the Intra's own layout classes.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_DENSITY,
    options: [
      { label: "Intra default", value: "default" },
      { label: "Compact", value: "compact" },
      { label: "Comfortable", value: "comfortable" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_HIDE_FOOTER",
    label: "Hide the footer",
    desc: "Removes the page footer on every Intra page.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.CUSTOM_HIDE_FOOTER,
    grid: true,
    colSpan: 1,
  },
  { feature: "customize", label: "Typography", kind: "divider" },
  {
    feature: "customize",
    key: "CUSTOM_FONT",
    label: "Font",
    desc: "Font family used on every Intra page. System fonts only, nothing is downloaded.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_FONT,
    options: [
      { label: "Intra default", value: "default" },
      { label: "System UI", value: "system" },
      { label: "Humanist (Segoe / Helvetica)", value: "humanist" },
      { label: "Rounded", value: "rounded" },
      { label: "Serif", value: "serif" },
      { label: "Monospace", value: "mono" },
      { label: "Custom…", value: "custom" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_FONT_FAMILY",
    label: "Custom font family",
    desc: "CSS font-family value, e.g. 'Fira Sans', sans-serif. Used when Font is set to Custom.",
    kind: "text",
    placeholder: "'Fira Sans', sans-serif",
    defaultValue: CONFIG_DEFAULT.CUSTOM_FONT_FAMILY,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_FONT_SCALE",
    label: "Size (%)",
    desc: "Scales the whole interface: 90 for a denser layout, 110 for larger text. 70–140.",
    kind: "number",
    min: 70,
    max: 140,
    step: 5,
    defaultValue: CONFIG_DEFAULT.CUSTOM_FONT_SCALE,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "customize",
    key: "CUSTOM_RADIUS",
    label: "Corners",
    desc: "Roundness of cards, buttons and inputs.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.CUSTOM_RADIUS,
    options: [
      { label: "Intra default", value: "default" },
      { label: "Square", value: "none" },
      { label: "Slightly rounded", value: "small" },
      { label: "Rounded", value: "large" },
      { label: "Very rounded", value: "full" },
    ],
    grid: true,
    colSpan: 1,
  },
  { feature: "customize", label: "Custom CSS", kind: "divider" },
  {
    feature: "customize",
    key: "CUSTOM_CSS",
    label: "Custom CSS",
    desc: "Applied last on every Intra page, on top of the theme and the settings above. Reload the page to undo a broken rule.",
    kind: "textarea",
    placeholder: "/* example */\n.dash-main { gap: 2rem; }",
    defaultValue: CONFIG_DEFAULT.CUSTOM_CSS,
    fullWidth: true,
  },
];
