/**
 * Logtime tab of the settings hub: monthly goal, average and day labels, the
 * emoji earnings counter, and the colours of the calendar.
 */
import { CONFIG_DEFAULT } from "../../../core/config.ts";
import { RAINBOW_PALETTES } from "../../logtime/rainbow-presets.ts";
import type { HubSettingDef } from "../hubSettings.data.ts";

export const LOGTIME_SETTINGS: readonly HubSettingDef[] = [
  {
    feature: "logtime",
    key: "LOGTIME_GOAL_HOURS",
    label: "Monthly goal",
    desc: "Sets the target number of hours (at least 1).",
    kind: "number",
    min: 1,
    step: 1,
    defaultValue: CONFIG_DEFAULT.LOGTIME_GOAL_HOURS,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "logtime",
    key: "LOGTIME_SHOW_AVERAGE",
    label: "Show average",
    desc: "Displays average hours per active day.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.LOGTIME_SHOW_AVERAGE,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "logtime",
    key: "LOGTIME_SHOW_GOAL",
    label: "Show goal",
    desc: "Shows the goal indicator.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.LOGTIME_SHOW_GOAL,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "logtime",
    key: "LOGTIME_SHOW_DAYS_MODE",
    label: "Day labels mode",
    desc: "Chooses how the day labels are displayed.",
    kind: "radio-group",
    defaultValue: CONFIG_DEFAULT.LOGTIME_SHOW_DAYS_MODE,
    options: [
      { label: "17/04", value: "date" },
      { label: "17/04 (2 days ago)", value: "both" },
      { label: "2 days ago", value: "days" },
    ],
    grid: false,
  },

  { feature: "logtime", label: "Emoji & Earnings", kind: "divider" },

  {
    feature: "logtime",
    key: "LOGTIME_SHOW_TACOS",
    label: "Show emoji",
    desc: "Enables the emoji visual markers.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.LOGTIME_SHOW_TACOS,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "logtime",
    key: "LOGTIME_EMOJI",
    label: "Custom Emoji",
    desc: "Replace 🌮 with your favorite emoji.",
    kind: "emoji",
    placeholder: "🌮🌮🌮",
    defaultValue: CONFIG_DEFAULT.LOGTIME_EMOJI,
    grid: true,
    colSpan: 1,
    dependsOn: "LOGTIME_SHOW_TACOS",
  },
  {
    feature: "logtime",
    key: "LOGTIME_EMOJI_DIVISOR",
    label: "Emoji Value",
    desc: "Value of the emoji (more than 0).",
    kind: "number",
    min: 0.1,
    step: 0.1,
    defaultValue: CONFIG_DEFAULT.LOGTIME_EMOJI_DIVISOR,
    grid: true,
    colSpan: 1,
    dependsOn: "LOGTIME_SHOW_TACOS",
  },
  {
    feature: "logtime",
    key: "LOGTIME_EMOJI_RATE",
    label: "Hourly Earning",
    desc: "How much you earn per hour.",
    kind: "number",
    min: 0,
    step: 0.1,
    defaultValue: CONFIG_DEFAULT.LOGTIME_EMOJI_RATE,
    grid: true,
    colSpan: 1,
    dependsOn: "LOGTIME_SHOW_TACOS",
  },
  {
    feature: "logtime",
    key: "LOGTIME_MAX_EARNINGS",
    label: "Max Earnings",
    desc: "Cap on total earnings per month (0 for no cap).",
    kind: "number",
    min: 0,
    step: 1,
    defaultValue: CONFIG_DEFAULT.LOGTIME_MAX_EARNINGS,
    grid: true,
    colSpan: 1,
    dependsOn: "LOGTIME_SHOW_TACOS",
  },

  { feature: "logtime", label: "Appearance", kind: "divider" },

  {
    feature: "logtime",
    key: "LOGTIME_CALENDAR_COLOR",
    label: "Calendar color",
    desc: "Accent color used for the calendar.",
    kind: "color",
    placeholder: "#00BCBA",
    defaultValue: CONFIG_DEFAULT.LOGTIME_CALENDAR_COLOR,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "logtime",
    key: "LOGTIME_LABELS_COLOR",
    label: "Labels color",
    desc: "Accent color used for labels and totals.",
    kind: "color",
    placeholder: "#26a641",
    defaultValue: CONFIG_DEFAULT.LOGTIME_LABELS_COLOR,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "logtime",
    key: "LOGTIME_RAINBOW_PALETTE",
    label: "Rainbow colors",
    desc: "Gradient shown when you reach your monthly goal.",
    kind: "rainbow-palette",
    defaultValue: CONFIG_DEFAULT.LOGTIME_RAINBOW_PALETTE,
    options: Object.entries(RAINBOW_PALETTES).map(([id, p]) => ({
      value: id,
      label: p.label,
      color: p.colors.join(", "),
    })),
    grid: true,
    colSpan: 1,
  },
];
