/**
 * Profile tab of the settings hub: theme accent, dashboard card order, the
 * cards the profile page shows, then the public profile section, which has a
 * contract of its own and lives in profile-public.ts.
 */
import { CONFIG_DEFAULT } from "../../../core/config.ts";
import type { HubSettingDef } from "../hubSettings.data.ts";
import { PUBLIC_PROFILE_SETTINGS } from "./profile-public.ts";

export const PROFILE_SETTINGS: readonly HubSettingDef[] = [
  {
    feature: "profile",
    label: "Appearance",
    kind: "divider",
  },
  {
    feature: "profile",
    key: "PROFILE_THEME_PRESET",
    label: "Theme accent",
    desc: "Change the accent color used across the intranet.",
    kind: "theme-preset",
    fullWidth: true,
    defaultValue: CONFIG_DEFAULT.PROFILE_THEME_PRESET,
    options: [
      { label: "Dark" },
      { label: "Default Dark", value: "dark", color: "199 89% 48%" },
      { label: "Neon", value: "neon", color: "324 100% 50%" },
      { label: "Synthwave", value: "synthwave", color: "327 92% 68%" },
      { label: "Forest", value: "forest", color: "141 71% 42%" },
      { label: "Halloween", value: "halloween", color: "34 100% 50%" },
      { label: "Dracula", value: "dracula", color: "326 100% 74%" },
      { label: "Night", value: "night", color: "199 93% 60%" },
      { label: "Sunset", value: "sunset", color: "16 100% 68%" },
      { label: "Luxury", value: "luxury", color: "0 0% 100%" },
      { label: "Cyberpunk", value: "cyberpunk", color: "341 100% 70%" },
      { label: "Arthur", value: "dim", color: "108 66% 73%" },
      { label: "Black", value: "black", color: "0 0% 23%" },
      { label: "Aubergine", value: "coffee", color: "30 66% 58%" },
      { label: "Aqua", value: "aqua", color: "182 90% 51%" },
      { divider: true },
      { label: "Light" },
      { label: "Default Light", value: "light", color: "181 100% 37%" },
      { label: "Cupcake", value: "cupcake", color: "183 47% 59%" },
      { label: "Bumblebee", value: "bumblebee", color: "45 100% 44%" },
      { label: "Emerald", value: "emerald", color: "141 50% 60%" },
      { label: "Corporate", value: "corporate", color: "223 49% 53%" },
      { label: "Retro", value: "retro", color: "10 70% 62%" },
      { label: "Valentine", value: "valentine", color: "346 79% 65%" },
      { label: "Garden", value: "garden", color: "0 65% 54%" },
      { label: "Lofi", value: "lofi", color: "0 0% 16%" },
      { label: "Pastel", value: "pastel", color: "295 47% 82%" },
      { label: "Fantasy", value: "fantasy", color: "285 60% 40%" },
      { label: "Wireframe", value: "wireframe", color: "0 0% 87%" },
      { label: "Cmyk", value: "cmyk", color: "220 62% 55%" },
      { label: "Autumn", value: "autumn", color: "11 56% 35%" },
      { label: "Acid", value: "acid", color: "319 57% 51%" },
      { label: "Lemonade", value: "lemonade", color: "106 50% 42%" },
      { label: "Winter", value: "winter", color: "226 59% 52%" },
      { label: "Nord", value: "nord", color: "211 37% 54%" },
      { label: "Caramellatte", value: "caramellatte", color: "0 0% 0%" },
      { label: "Silk", value: "silk", color: "230 21% 23%" },
      { label: "Soap", value: "soap", color: "4 68% 66%" },
      { label: "Citrus", value: "citrus", color: "51 100% 50%" },
    ],
  },
  {
    feature: "profile",
    key: "PROFILE_CARD_ORDER",
    label: "Dashboard Cards Order",
    desc: "Drag and drop the colored cards to prioritize your dashboard sections.",
    kind: "card-order",
    fullWidth: true,
    defaultValue: CONFIG_DEFAULT.PROFILE_CARD_ORDER,
  },
  {
    feature: "profile",
    key: "PROFILE_USE_CUSTOM_COLOR",
    label: "Use custom color on card",
    desc: "Applies the logtime calendar color to the profile card.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_USE_CUSTOM_COLOR,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_USE_MODERN_INFO_CARD",
    label: "Modern info card",
    desc: "Replace the native stats bar with sleek info badges.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_USE_MODERN_INFO_CARD,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    label: "Achievements",
    kind: "divider",
  },
  {
    feature: "profile",
    key: "PROFILE_SHOW_ACHIEVEMENTS",
    label: "Show all achievements",
    desc: "Replaces the native achievements card with a scrollable list of all achievements.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_SHOW_ACHIEVEMENTS,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    label: "Projects",
    kind: "divider",
  },
  {
    feature: "profile",
    key: "PROFILE_SHOW_MARKS",
    label: "Show past marks",
    desc: "Adds a list of completed project marks in the Projects card.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_SHOW_MARKS,
    grid: true,
    colSpan: 1,
    // No requiresCloud: the list is read from intrapy with the page's own
    // Intra token and login (marks.ts), so it runs signed out too, and a
    // signed-out student must be able to turn it off.
  },
  {
    feature: "profile",
    key: "PROFILE_MARKS_SORT_ORDER",
    label: "Marks sort order",
    desc: "Sort completed projects by date.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.PROFILE_MARKS_SORT_ORDER,
    options: [
      { label: "Newest first", value: "newest_first" },
      { label: "Oldest first", value: "oldest_first" },
    ],
    grid: true,
    colSpan: 1,
    dependsOn: "PROFILE_SHOW_MARKS",
  },
  {
    feature: "profile",
    key: "PROFILE_PROJECTS_SORT",
    label: "Projects sort",
    desc: "Adds a sort dropdown to the Marks list on user profiles.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_PROJECTS_SORT,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_MARKS_SHOW_REAL_DATE",
    label: "Enhance marks display",
    desc: `Replaces relative dates with absolute dates (e.g. "19/06/26 11:13") on other users' profiles.`,
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_MARKS_SHOW_REAL_DATE,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    label: "Events",
    kind: "divider",
  },
  {
    feature: "profile",
    key: "PROFILE_EVENT_TYPE_FILTER",
    label: "Event visibility",
    desc: "Choose which types of events you want to see.",
    kind: "radio-group",
    defaultValue: CONFIG_DEFAULT.PROFILE_EVENT_TYPE_FILTER,
    options: [],
  },

  // Last on purpose: the public section closes the tab, behind its divider
  // (tests/hub-public-profile.test.ts).
  ...PUBLIC_PROFILE_SETTINGS,
];
