/**
 * Public profile section of the Profile tab: what a student publishes on
 * their profile for every Better Intra user to see, plus the viewer switch
 * for other people's extras.
 *
 * src/features/profile/extras/extras.ts is the contract. Everything typed
 * here is read by strangers: the option values and the maxLength below mirror
 * the enums and LIMITS of the contract (tests/hub-public-profile.test.ts
 * enforces it), and the sanitizer, not this form, is what makes a value safe
 * to display.
 */
import { CONFIG_DEFAULT } from "../../../core/config.ts";
// Only the limits: an input of the public profile section stops where the
// sanitizer of the extras would cut, so nothing typed is silently lost.
import { LIMITS } from "../../profile/extras/extras.ts";
import type { HubSettingDef } from "../hubSettings.data.ts";
import { BG_PRESET_OPTIONS } from "./options.ts";

export const PUBLIC_PROFILE_SETTINGS: readonly HubSettingDef[] = [
  {
    feature: "profile",
    label: "Public profile (visible to every Better Intra user)",
    kind: "divider",
  },
  {
    // No colSpan: the master switch takes the whole row, its description
    // is the one place that says who sees what follows.
    feature: "profile",
    key: "PROFILE_PUB_ENABLED",
    label: "Publish my profile extras",
    desc: "Everything below is shown to every Better Intra user who opens your profile. It needs the cloud account to reach them; on your own page it shows immediately.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_ENABLED,
  },

  { feature: "profile", label: "Identity", kind: "divider" },
  {
    feature: "profile",
    key: "PROFILE_PUB_STATUS_EMOJI",
    label: "Status emoji",
    desc: "Shown in front of your status.",
    kind: "emoji",
    placeholder: "💻",
    // long emoji sequences (flags, families) need more than the default 6
    maxLength: LIMITS.statusEmoji,
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_STATUS_EMOJI,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_STATUS_TEXT",
    label: "Status",
    desc: `What you are up to right now. Up to ${LIMITS.statusText} characters.`,
    kind: "text",
    maxLength: LIMITS.statusText,
    placeholder: "Grinding C09",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_STATUS_TEXT,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_PRONOUNS",
    label: "Pronouns",
    desc: `Up to ${LIMITS.pronouns} characters.`,
    kind: "text",
    maxLength: LIMITS.pronouns,
    placeholder: "she/her",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_PRONOUNS,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_FLAIR",
    label: "Flair",
    desc: `Up to ${LIMITS.flairItems} emoji separated by spaces.`,
    kind: "text",
    maxLength: 60,
    placeholder: "🎯 🚀 ☕",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_FLAIR,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_BIO",
    label: "Bio",
    desc: `A few words about you, shown under your name. Plain text, up to ${LIMITS.bio} characters.`,
    kind: "text",
    fullWidth: true,
    maxLength: LIMITS.bio,
    placeholder: "42 student, C enjoyer, powered by coffee.",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_BIO,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_GREETING",
    label: "Visitor greeting",
    desc: `Shown once to people who visit your profile. Up to ${LIMITS.greeting} characters.`,
    kind: "text",
    fullWidth: true,
    maxLength: LIMITS.greeting,
    placeholder: "Welcome to my profile!",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_GREETING,
  },

  { feature: "profile", label: "Links", kind: "divider" },
  {
    feature: "profile",
    key: "PROFILE_PUB_LINK_GITHUB",
    linkKind: "github",
    label: "GitHub",
    desc: "User name or profile URL.",
    kind: "text",
    placeholder: "octocat",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_LINK_GITHUB,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_LINK_GITLAB",
    linkKind: "gitlab",
    label: "GitLab",
    desc: "User name or profile URL.",
    kind: "text",
    placeholder: "user name",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_LINK_GITLAB,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_LINK_LINKEDIN",
    linkKind: "linkedin",
    label: "LinkedIn",
    desc: "User name or profile URL.",
    kind: "text",
    placeholder: "your-name",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_LINK_LINKEDIN,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_LINK_WEBSITE",
    linkKind: "website",
    label: "Website",
    desc: "Your own site or portfolio. https only.",
    kind: "text",
    placeholder: "https://example.com",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_LINK_WEBSITE,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_LINK_DISCORD",
    linkKind: "discord",
    label: "Discord",
    desc: "Your handle. Visitors copy it with a click.",
    kind: "text",
    placeholder: "handle",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_LINK_DISCORD,
    grid: true,
    colSpan: 1,
  },

  { feature: "profile", label: "Name", kind: "divider" },
  {
    feature: "profile",
    key: "PROFILE_PUB_NAME_STYLE",
    label: "Name style",
    desc: "How your name is drawn on your profile.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_NAME_STYLE,
    options: [
      { label: "Intra default", value: "default" },
      { label: "Accent colour", value: "accent" },
      { label: "Custom colour", value: "custom" },
      { label: "Two-colour gradient", value: "gradient" },
      { label: "Rainbow", value: "rainbow" },
      { label: "Glow", value: "glow" },
      { label: "Neon", value: "neon" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_NAME_COLOR",
    label: "Name colour",
    desc: "Used by the custom, gradient, glow and neon styles.",
    kind: "color",
    placeholder: "#00babc",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_NAME_COLOR,
    dependsOn: "PROFILE_PUB_NAME_STYLE",
    dependsOnValues: ["custom", "gradient", "glow", "neon"],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_NAME_COLOR_2",
    label: "Second name colour",
    desc: "Second colour of the gradient and of the neon halo.",
    kind: "color",
    placeholder: "#7c3aed",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_NAME_COLOR_2,
    dependsOn: "PROFILE_PUB_NAME_STYLE",
    dependsOnValues: ["gradient", "neon"],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_NAME_FONT",
    label: "Name font",
    desc: "Font of your name. Presets made of system fonts only, nothing is downloaded.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_NAME_FONT,
    options: [
      { label: "Intra default", value: "default" },
      { label: "System UI", value: "system" },
      { label: "Humanist (Segoe / Helvetica)", value: "humanist" },
      { label: "Rounded", value: "rounded" },
      { label: "Serif", value: "serif" },
      { label: "Monospace", value: "mono" },
    ],
    grid: true,
    colSpan: 1,
  },

  { feature: "profile", label: "Avatar frame", kind: "divider" },
  {
    feature: "profile",
    key: "PROFILE_PUB_FRAME",
    label: "Avatar frame",
    desc: "Ring drawn around your profile picture.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_FRAME,
    options: [
      { label: "None", value: "none" },
      { label: "Solid ring", value: "solid" },
      { label: "Double ring", value: "double" },
      { label: "Dashed ring", value: "dashed" },
      { label: "Gradient ring", value: "gradient" },
      { label: "Rainbow ring", value: "rainbow" },
      { label: "Glow", value: "glow" },
      { label: "Neon", value: "neon" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_FRAME_COLOR",
    label: "Frame colour",
    desc: "Used by every frame but the rainbow ring, which has its own colours.",
    kind: "color",
    placeholder: "#00babc",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_FRAME_COLOR,
    dependsOn: "PROFILE_PUB_FRAME",
    dependsOnValues: ["solid", "double", "dashed", "gradient", "glow", "neon"],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_FRAME_COLOR_2",
    label: "Second frame colour",
    desc: "Second colour of the double, gradient and neon rings.",
    kind: "color",
    placeholder: "#7c3aed",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_FRAME_COLOR_2,
    dependsOn: "PROFILE_PUB_FRAME",
    dependsOnValues: ["double", "gradient", "neon"],
    grid: true,
    colSpan: 1,
  },

  { feature: "profile", label: "Level bar", kind: "divider" },
  {
    feature: "profile",
    key: "PROFILE_PUB_LEVEL_STYLE",
    label: "Level bar style",
    desc: "Fill of the level progress bar on your profile.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_LEVEL_STYLE,
    options: [
      { label: "Intra default", value: "default" },
      { label: "Custom colour", value: "custom" },
      { label: "Gradient", value: "gradient" },
      { label: "Rainbow", value: "rainbow" },
      { label: "Animated stripes", value: "striped" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_LEVEL_COLOR",
    label: "Level bar colour",
    desc: "Used by the custom, gradient and striped styles.",
    kind: "color",
    placeholder: "#00babc",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_LEVEL_COLOR,
    dependsOn: "PROFILE_PUB_LEVEL_STYLE",
    dependsOnValues: ["custom", "gradient", "striped"],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_LEVEL_COLOR_2",
    label: "Second level bar colour",
    desc: "End colour of the gradient style.",
    kind: "color",
    placeholder: "#7c3aed",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_LEVEL_COLOR_2,
    dependsOn: "PROFILE_PUB_LEVEL_STYLE",
    dependsOnValues: ["gradient"],
    grid: true,
    colSpan: 1,
  },

  { feature: "profile", label: "Header & card", kind: "divider" },
  {
    feature: "profile",
    key: "PROFILE_PUB_BANNER_GRADIENT",
    label: "Header gradient",
    desc: "Built-in gradient behind your profile header, used when you have no header image.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_BANNER_GRADIENT,
    options: BG_PRESET_OPTIONS,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_BANNER_DIM",
    label: "Darken header (%)",
    desc: `Dark overlay on your header to keep the text readable. 0–${LIMITS.bannerDimMax}.`,
    kind: "number",
    min: 0,
    max: LIMITS.bannerDimMax,
    step: 5,
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_BANNER_DIM,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_BANNER_BLUR",
    label: "Card blur (px)",
    desc: `Blurs what is behind the profile card. 0–${LIMITS.bannerBlurMax}.`,
    kind: "number",
    min: 0,
    max: LIMITS.bannerBlurMax,
    step: 1,
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_BANNER_BLUR,
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_CARD_GLOW",
    label: "Profile card glow",
    desc: "Soft halo around your profile card.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_CARD_GLOW,
    grid: true,
    colSpan: 1,
  },

  { feature: "profile", label: "Effect", kind: "divider" },
  {
    feature: "profile",
    key: "PROFILE_PUB_EFFECT",
    label: "Page effect",
    desc: "Animated particles over your profile page.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_EFFECT,
    options: [
      { label: "None", value: "none" },
      { label: "Snow", value: "snow" },
      { label: "Stars", value: "stars" },
      { label: "Fireflies", value: "fireflies" },
      { label: "Confetti", value: "confetti" },
      { label: "Bubbles", value: "bubbles" },
      { label: "Sakura", value: "sakura" },
      { label: "Rain", value: "rain" },
      { label: "Embers", value: "embers" },
    ],
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_EFFECT_INTENSITY",
    label: "Effect intensity",
    desc: "How many particles are drawn.",
    kind: "select",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_EFFECT_INTENSITY,
    options: [
      { label: "Low", value: "low" },
      { label: "Medium", value: "medium" },
      { label: "High", value: "high" },
    ],
    dependsOn: "PROFILE_PUB_EFFECT",
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_EFFECT_TINT",
    label: "Tint the effect",
    desc: "Use your own colour instead of the effect's colours.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_EFFECT_TINT,
    dependsOn: "PROFILE_PUB_EFFECT",
    grid: true,
    colSpan: 1,
  },
  {
    feature: "profile",
    key: "PROFILE_PUB_EFFECT_COLOR",
    label: "Effect colour",
    desc: "Colour of the particles.",
    kind: "color",
    placeholder: "#ffffff",
    defaultValue: CONFIG_DEFAULT.PROFILE_PUB_EFFECT_COLOR,
    dependsOn: "PROFILE_PUB_EFFECT_TINT",
    grid: true,
    colSpan: 1,
  },

  // Viewer side: not published, it decides what this browser displays.
  { feature: "profile", label: "Other people's profiles", kind: "divider" },
  {
    feature: "profile",
    key: "PROFILE_SHOW_OTHERS_EXTRAS",
    label: "Show other people's profile extras",
    desc: "Bios, styles and effects other students publish on their profile. Turn off to see plain profiles.",
    kind: "toggle",
    defaultValue: CONFIG_DEFAULT.PROFILE_SHOW_OTHERS_EXTRAS,
    grid: true,
    colSpan: 1,
  },
];
