import CLOCK from "../../assets/svg/clock.svg?raw";
import CALENDAR from "../../assets/svg/calendar.svg?raw";
import CLUSTERS from "../../assets/svg/clusters.svg?raw";
import USER from "../../assets/svg/user.svg?raw";
import SHORTCUT from "../../assets/svg/shortcut.svg?raw";
import ABOUT from "../../assets/svg/about.svg?raw";
import DISCORD_SVG from "../../assets/svg/discord.svg?raw";
import ADVANCED_SVG from "../../assets/svg/advanced.svg?raw";
import GRID_SVG from "../../assets/svg/grid.svg?raw";
import CUSTOMIZE_SVG from "../../assets/svg/sun.svg?raw";
import { CONFIG_DEFAULT, ConfigKey } from "../../config.ts";
import { CLUSTERS as CLUSTER_OPTIONS } from "../clusters/clusters.data.ts";
import { RAINBOW_PALETTES } from "../logtime/rainbow-presets.ts";

// Repository links come from package.json "repository" (see scripts/repo-info.js)
export const HUB_INFO = {
  name: "Better Intra",
  version: __APP_VERSION__,
  author: __REPO_URL__.replace(/\/[^/]+$/, ""),
  github: __REPO_URL__,
  issues: `${__REPO_URL__}/issues`,
  upstream: "https://github.com/nicopasla/better-intra",
  license: "MIT",
} as const;

export const FEATURE_DEFS = [
  {
    id: "profile",
    name: "Profile",
    icon: USER,
    desc: "Improves readability and allows local profile/background image customization.",
    cols: 2,
  },
  {
    id: "extras",
    name: "Extras",
    icon: GRID_SVG,
    desc: "Enable or disable optional add-ons. More can be added later.",
    cols: 3,
  },
  {
    id: "clusters",
    name: "Clusters",
    icon: CLUSTERS,
    desc: "Adds 'chair' direction markers and a default cluster picker with saved preference.",
    cols: 2,
  },
  {
    id: "logtime",
    name: "Logtime",
    icon: CLOCK,
    desc: "Redesign the logtime to show weekly and total hours.",
    cols: 3,
  },
  {
    id: "shortcuts",
    name: "Shortcuts",
    icon: SHORTCUT,
    desc: "Manage custom navigation links.",
    cols: 3,
  },
  {
    id: "discord",
    name: "Discord",
    icon: DISCORD_SVG,
    desc: "Get evaluation reminders via Discord DM.",
  },
  {
    id: "calendar",
    name: "Calendar",
    icon: CALENDAR,
    desc: "Subscribe to your 42 events in Google Calendar, Apple Calendar, or any calendar app.",
  },
  {
    id: "customize",
    name: "Customize",
    icon: CUSTOMIZE_SVG,
    desc: "Accent colour, fonts, size, corners and your own CSS on every Intra page.",
    cols: 2,
  },
  {
    id: "advanced",
    name: "Advanced",
    icon: ADVANCED_SVG,
    desc: "General behavior settings.",
    cols: 2,
  },
  {
    id: "about",
    name: "About",
    icon: ABOUT,
    desc: "Information about Better Intra and its technical stack.",
  },
] as const;

export type FeatureId = (typeof FEATURE_DEFS)[number]["id"];
export const FEATURE_IDS = new Set<FeatureId>(FEATURE_DEFS.map((f) => f.id));

export const STORAGE_KEY = "ACTIVE_SCRIPTS";

export type SettingKind =
  | "toggle"
  | "number"
  | "text"
  | "textarea"
  | "custom-presets"
  | "custom-cards"
  | "url"
  | "select"
  | "color"
  | "radio-group"
  | "divider"
  | "shortcuts"
  | "emoji"
  | "about"
  | "card-order"
  | "action"
  | "discord-panel"
  | "calendar-panel"
  | "theme-preset"
  | "rainbow-palette"
  | "campus-info"
  | "feature-cards";

export { INTRA_FONT } from "../logtime/constants.ts";

export type FeatureCardOption = {
  label?: string;
  value?: string;
  color?: string;
  desc?: string;
  divider?: boolean;
  dependsOn?: ConfigKey;
  requiresCloud?: boolean;
  big?: boolean;
  subToggle?: {
    label: string;
    value: string;
    desc?: string;
    requiresCloud?: boolean;
    dependsOn?: ConfigKey;
  };
};

export type HubSettingDef = {
  feature: FeatureId;
  label: string;
  key?: ConfigKey;
  desc?: string;
  kind: SettingKind;
  nullable?: boolean;
  defaultValue?: unknown;
  options?: readonly FeatureCardOption[];
  grid?: boolean;
  colSpan?: number;
  fullWidth?: boolean;
  dependsOn?: ConfigKey;
  requiresCloud?: boolean;
  min?: number;
  max?: number;
  step?: number;
  placeholder?: string;
  actionLabel?: string;
  actionType?: "export" | "import" | "reset" | "backup" | "reload-campus";
};

export const HUB_SETTING_DEFS: Record<FeatureId, readonly HubSettingDef[]> = {
  logtime: [
    {
      feature: "logtime",
      key: "LOGTIME_GOAL_HOURS",
      label: "Monthly goal",
      desc: "Sets the target number of hour.",
      kind: "number",
      min: 0,
      step: 1,
      defaultValue: CONFIG_DEFAULT.LOGTIME_GOAL_HOURS,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "logtime",
      key: "LOGTIME_SHOW_AVERAGE",
      label: "Show average",
      desc: "Displays average hours per active day.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.LOGTIME_SHOW_AVERAGE,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "logtime",
      key: "LOGTIME_SHOW_GOAL",
      label: "Show goal",
      desc: "Shows the goal indicator.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.LOGTIME_SHOW_GOAL,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "logtime",
      key: "LOGTIME_SHOW_DAYS_MODE",
      label: "Day labels mode",
      desc: "Chooses how the day labels are displayed.",
      kind: "radio-group",
      defaultValue: CONFIG_DEFAULT.LOGTIME_SHOW_DAYS_MODE,
      options: [
        { label: "17/04", value: "date" },
        { label: "17/04 (2 days ago)", value: "both" },
        { label: "2 days ago", value: "days" },
      ],
      grid: false,
    },

    { feature: "logtime", label: "Emoji & Earnings", kind: "divider" },

    {
      feature: "logtime",
      key: "LOGTIME_SHOW_TACOS",
      label: "Show emoji",
      desc: "Enables the emoji visual markers.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.LOGTIME_SHOW_TACOS,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "logtime",
      key: "LOGTIME_EMOJI",
      label: "Custom Emoji",
      desc: "Replace 🌮 with your favorite emoji.",
      kind: "emoji",
      placeholder: "🌮🌮🌮",
      defaultValue: CONFIG_DEFAULT.LOGTIME_EMOJI,
      grid: true,
      colSpan: 1,
      dependsOn: "LOGTIME_SHOW_TACOS",
    },
    {
      feature: "logtime",
      key: "LOGTIME_EMOJI_DIVISOR",
      label: "Emoji Value",
      desc: "Value of the emoji.",
      kind: "number",
      defaultValue: CONFIG_DEFAULT.LOGTIME_EMOJI_DIVISOR,
      grid: true,
      colSpan: 1,
      dependsOn: "LOGTIME_SHOW_TACOS",
    },
    {
      feature: "logtime",
      key: "LOGTIME_EMOJI_RATE",
      label: "Hourly Earning",
      desc: "How much you earn per hour.",
      kind: "number",
      defaultValue: CONFIG_DEFAULT.LOGTIME_EMOJI_RATE,
      grid: true,
      colSpan: 1,
      dependsOn: "LOGTIME_SHOW_TACOS",
    },
    {
      feature: "logtime",
      key: "LOGTIME_MAX_EARNINGS",
      label: "Max Earnings",
      desc: "Cap on total earnings per month.",
      kind: "number",
      defaultValue: CONFIG_DEFAULT.LOGTIME_MAX_EARNINGS,
      grid: true,
      colSpan: 1,
      dependsOn: "LOGTIME_SHOW_TACOS",
    },

    { feature: "logtime", label: "Appearance", kind: "divider" },

    {
      feature: "logtime",
      key: "LOGTIME_CALENDAR_COLOR",
      label: "Calendar color",
      desc: "Accent color used for the calendar.",
      kind: "color",
      placeholder: "#00BCBA",
      defaultValue: CONFIG_DEFAULT.LOGTIME_CALENDAR_COLOR,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "logtime",
      key: "LOGTIME_LABELS_COLOR",
      label: "Labels color",
      desc: "Accent color used for labels and totals.",
      kind: "color",
      placeholder: "#26a641",
      defaultValue: CONFIG_DEFAULT.LOGTIME_LABELS_COLOR,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "logtime",
      key: "LOGTIME_RAINBOW_PALETTE",
      label: "Rainbow colors",
      desc: "Gradient shown when you reach your monthly goal.",
      kind: "rainbow-palette",
      defaultValue: CONFIG_DEFAULT.LOGTIME_RAINBOW_PALETTE,
      options: Object.entries(RAINBOW_PALETTES).map(([id, p]) => ({
        value: id,
        label: p.label,
        color: p.colors.join(", "),
      })),
      grid: true,
      colSpan: 1,
    },
  ],
  clusters: [
    {
      feature: "clusters",
      key: "CLUSTERS_SHOW_MARKERS",
      label: "Show markers",
      desc: "Shows the direction markers on the cluster screen.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CLUSTERS_SHOW_MARKERS,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "clusters",
      key: "CLUSTERS_OPEN_NEW_TAB",
      label: "Open profiles in new tab",
      desc: "When clicking a user on the clusters map, opens their profile in a new tab.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CLUSTERS_OPEN_NEW_TAB,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "clusters",
      key: "CLUSTERS_DEFAULT_ID",
      label: "Default cluster",
      desc: "Prefills a cluster page when the page opens.",
      kind: "select",
      defaultValue: String(CONFIG_DEFAULT.CLUSTERS_DEFAULT_ID),
      options: CLUSTER_OPTIONS.map((c) => ({
        label: c.name.toUpperCase(),
        value: c.id,
      })),
      grid: true,
      colSpan: 1,
    },
  ],
  profile: [
    {
      feature: "profile",
      label: "Appearance",
      kind: "divider",
    },
    {
      feature: "profile",
      key: "PROFILE_THEME_PRESET",
      label: "Theme accent",
      desc: "Change the accent color used across the intranet.",
      kind: "theme-preset",
      fullWidth: true,
      defaultValue: CONFIG_DEFAULT.PROFILE_THEME_PRESET,
      options: [
        { label: "Dark" },
        { label: "Default Dark", value: "dark", color: "199 89% 48%" },
        { label: "Neon", value: "neon", color: "324 100% 50%" },
        { label: "Synthwave", value: "synthwave", color: "327 92% 68%" },
        { label: "Forest", value: "forest", color: "141 71% 42%" },
        { label: "Halloween", value: "halloween", color: "34 100% 50%" },
        { label: "Dracula", value: "dracula", color: "326 100% 74%" },
        { label: "Night", value: "night", color: "199 93% 60%" },
        { label: "Sunset", value: "sunset", color: "16 100% 68%" },
        { label: "Luxury", value: "luxury", color: "0 0% 100%" },
        { label: "Cyberpunk", value: "cyberpunk", color: "341 100% 70%" },
        { label: "Arthur", value: "dim", color: "108 66% 73%" },
        { label: "Black", value: "black", color: "0 0% 23%" },
        { label: "Aubergine", value: "coffee", color: "30 66% 58%" },
        { label: "Aqua", value: "aqua", color: "182 90% 51%" },
        { divider: true },
        { label: "Light" },
        { label: "Default Light", value: "light", color: "181 100% 37%" },
        { label: "Cupcake", value: "cupcake", color: "183 47% 59%" },
        { label: "Bumblebee", value: "bumblebee", color: "45 100% 44%" },
        { label: "Emerald", value: "emerald", color: "141 50% 60%" },
        { label: "Corporate", value: "corporate", color: "223 49% 53%" },
        { label: "Retro", value: "retro", color: "10 70% 62%" },
        { label: "Valentine", value: "valentine", color: "346 79% 65%" },
        { label: "Garden", value: "garden", color: "0 65% 54%" },
        { label: "Lofi", value: "lofi", color: "0 0% 16%" },
        { label: "Pastel", value: "pastel", color: "295 47% 82%" },
        { label: "Fantasy", value: "fantasy", color: "285 60% 40%" },
        { label: "Wireframe", value: "wireframe", color: "0 0% 87%" },
        { label: "Cmyk", value: "cmyk", color: "220 62% 55%" },
        { label: "Autumn", value: "autumn", color: "11 56% 35%" },
        { label: "Acid", value: "acid", color: "319 57% 51%" },
        { label: "Lemonade", value: "lemonade", color: "106 50% 42%" },
        { label: "Winter", value: "winter", color: "226 59% 52%" },
        { label: "Nord", value: "nord", color: "211 37% 54%" },
        { label: "Caramellatte", value: "caramellatte", color: "0 0% 0%" },
        { label: "Silk", value: "silk", color: "230 21% 23%" },
        { label: "Soap", value: "soap", color: "4 68% 66%" },
        { label: "Citrus", value: "citrus", color: "51 100% 50%" },
      ],
    },
    {
      feature: "profile",
      key: "PROFILE_CARD_ORDER",
      label: "Dashboard Cards Order",
      desc: "Drag and drop the colored cards to prioritize your dashboard sections.",
      kind: "card-order",
      fullWidth: true,
      defaultValue: CONFIG_DEFAULT.PROFILE_CARD_ORDER,
    },
    {
      feature: "profile",
      key: "PROFILE_USE_CUSTOM_COLOR",
      label: "Use custom color on card",
      desc: "Applies the logtime calendar color to the profile card.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.PROFILE_USE_CUSTOM_COLOR,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "profile",
      key: "PROFILE_USE_MODERN_INFO_CARD",
      label: "Modern info card",
      desc: "Replace the native stats bar with sleek info badges.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.PROFILE_USE_MODERN_INFO_CARD,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "profile",
      label: "Achievements",
      kind: "divider",
    },
    {
      feature: "profile",
      key: "PROFILE_SHOW_ACHIEVEMENTS",
      label: "Show all achievements",
      desc: "Replaces the native achievements card with a scrollable list of all achievements.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.PROFILE_SHOW_ACHIEVEMENTS,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "profile",
      label: "Projects",
      kind: "divider",
    },
    {
      feature: "profile",
      key: "PROFILE_SHOW_MARKS",
      label: "Show past marks",
      desc: "Adds a list of completed project marks in the Projects card.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.PROFILE_SHOW_MARKS,
      grid: true,
      colSpan: 1,
      requiresCloud: true,
    },
    {
      feature: "profile",
      key: "PROFILE_MARKS_SORT_ORDER",
      label: "Marks sort order",
      desc: "Sort completed projects by date.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.PROFILE_MARKS_SORT_ORDER,
      options: [
        { label: "Newest first", value: "newest_first" },
        { label: "Oldest first", value: "oldest_first" },
      ],
      grid: true,
      colSpan: 1,
      dependsOn: "PROFILE_SHOW_MARKS",
      requiresCloud: true,
    },
    {
      feature: "profile",
      key: "PROFILE_PROJECTS_SORT",
      label: "Projects sort",
      desc: "Adds a sort dropdown to the Marks list on user profiles.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.PROFILE_PROJECTS_SORT,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "profile",
      key: "PROFILE_MARKS_SHOW_REAL_DATE",
      label: "Enhance marks display",
      desc: `Replaces relative dates with absolute dates (e.g. "19/06/26 11:13") on other users' profiles.`,
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.PROFILE_MARKS_SHOW_REAL_DATE,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "profile",
      label: "Events",
      kind: "divider",
    },
    {
      feature: "profile",
      key: "PROFILE_EVENT_TYPE_FILTER",
      label: "Event visibility",
      desc: "Choose which types of events you want to see.",
      kind: "radio-group",
      defaultValue: CONFIG_DEFAULT.PROFILE_EVENT_TYPE_FILTER,
      options: [],
    },
  ],
  shortcuts: [
    {
      feature: "shortcuts",
      key: "SHORTCUTS_LINKS",
      label: "",
      kind: "shortcuts",
      fullWidth: true,
    },
    {
      feature: "shortcuts",
      key: "SHORTCUTS_HIDE_IMPORTANT_LINKS",
      label: "Hide important links",
      desc: "Hides the default Intra important links on the profile to give shortcuts the full width.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.SHORTCUTS_HIDE_IMPORTANT_LINKS,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "shortcuts",
      key: "SHORTCUTS_ALIGNMENT",
      label: "Shortcuts alignment",
      desc: "Aligns shortcuts left, center, or right when important links are hidden.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.SHORTCUTS_ALIGNMENT,
      options: [
        { label: "Left", value: "left" },
        { label: "Center", value: "center" },
        { label: "Right", value: "right" },
      ] as const,
      dependsOn: "SHORTCUTS_HIDE_IMPORTANT_LINKS",
      grid: true,
      colSpan: 2,
    },
  ],
  discord: [
    {
      feature: "discord",
      label: "Discord",
      desc: "Notifications and account connection.",
      kind: "discord-panel",
      fullWidth: true,
    },
  ],
  extras: [
    {
      feature: "extras",
      label: "",
      kind: "feature-cards",
      fullWidth: true,
      options: [
        {
          label: "Subject tracker",
          value: "SUBJECT_TRACKER_ENABLED",
          color: "warning",
          big: true,
          desc: "Shows a badge on project pages when a subject has been updated, using update data shared by the community.",
          subToggle: {
            label: "Share with the community",
            value: "SUBJECT_TRACKER_SEND_DATA",
            requiresCloud: true,
            desc: "Send subject links so everyone sees when subjects are updated - and you benefit from updates others have spotted.",
          },
        },
        {
          label: "Friends widget",
          value: "SHOW_FRIENDS_WIDGET",
          color: "success",
          big: true,
          desc: "Adds the friends button and widget to your profile page.",
          subToggle: {
            label: "Show custom avatars in friends",
            value: "SHOW_CUSTOM_AVATARS_IN_FRIENDS",
            desc: "When available, displays friends custom profile pictures instead of 42 avatars.",
            dependsOn: "SHOW_FRIENDS_WIDGET",
          },
        },
        {
          label: "Pending evaluations",
          value: "PROFILE_SHOW_EVALUATIONS",
          color: "primary",
          big: true,
          desc: "Organizes the pending evaluations card into Evaluator and Evaluated sections.",
        },
        {
          label: "Thursday Roulette",
          value: "PROFILE_SHOW_ROULETTE",
          color: "info",
          big: true,
          desc: "Adds a card with roulette wins, points, and next draw countdown.",
          requiresCloud: true,
          subToggle: {
            label: "Show roulette history",
            value: "PROFILE_SHOW_ROULETTE_HISTORY",
            desc: "Displays the full timeline of past roulette wins inside the card.",
            dependsOn: "PROFILE_SHOW_ROULETTE",
            requiresCloud: true,
          },
        },
      ],
    },
  ],
  calendar: [
    {
      feature: "calendar",
      label: "Calendar Sync",
      desc: "Subscribe to your 42 events in your calendar app.",
      kind: "calendar-panel",
      fullWidth: true,
    },
  ],
  about: [
    {
      feature: "about",
      label: "",
      kind: "about",
      fullWidth: true,
    },
  ],
  customize: [
    {
      feature: "customize",
      label: "Presets & sharing",
      desc: "Save your look under a name, switch between presets, and share a theme code with friends.",
      kind: "custom-presets",
      fullWidth: true,
    },
    { feature: "customize", label: "Show your look to others", kind: "divider" },
    {
      feature: "customize",
      key: "CUSTOM_SHARE_LOOK",
      label: "Publish my look on my profile",
      desc: "Other Better Intra users see your accent, palette, background and card style when they open your profile. Fonts, size, scrollbar and custom CSS are never shared. Needs the cloud account.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CUSTOM_SHARE_LOOK,
      requiresCloud: true,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_SHOW_OTHERS_LOOK",
      label: "Show other people's looks",
      desc: "Apply the look a student published when you visit their profile. Turn off to always keep your own style.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CUSTOM_SHOW_OTHERS_LOOK,
      grid: true,
      colSpan: 1,
    },
    { feature: "customize", label: "Accent", kind: "divider" },
    {
      feature: "customize",
      key: "CUSTOM_ACCENT_ENABLED",
      label: "Custom accent colour",
      desc: "Use your own colour instead of the theme preset's accent.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CUSTOM_ACCENT_ENABLED,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_ACCENT_COLOR",
      label: "Accent colour",
      desc: "Buttons, links, highlights and progress bars across the intranet.",
      kind: "color",
      placeholder: "#00babc",
      defaultValue: CONFIG_DEFAULT.CUSTOM_ACCENT_COLOR,
      dependsOn: "CUSTOM_ACCENT_ENABLED",
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_ACCENT_GRADIENT",
      label: "Two-colour accent",
      desc: "Buttons and progress bars fade from the accent colour to a second one.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CUSTOM_ACCENT_GRADIENT,
      dependsOn: "CUSTOM_ACCENT_ENABLED",
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_ACCENT_COLOR_2",
      label: "Second colour",
      desc: "End colour of the accent gradient.",
      kind: "color",
      placeholder: "#7c3aed",
      defaultValue: CONFIG_DEFAULT.CUSTOM_ACCENT_COLOR_2,
      dependsOn: "CUSTOM_ACCENT_GRADIENT",
      grid: true,
      colSpan: 1,
    },
    { feature: "customize", label: "Colours", kind: "divider" },
    {
      feature: "customize",
      key: "CUSTOM_THEME_ENABLED",
      label: "Custom palette",
      desc: "Replace the theme's page, card and text colours with your own. Works best with the dark theme.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CUSTOM_THEME_ENABLED,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_THEME_BG",
      label: "Page colour",
      desc: "Background of the pages.",
      kind: "color",
      placeholder: "#1c2130",
      defaultValue: CONFIG_DEFAULT.CUSTOM_THEME_BG,
      dependsOn: "CUSTOM_THEME_ENABLED",
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_THEME_CARD",
      label: "Card colour",
      desc: "Cards, sidebar, popovers and inputs.",
      kind: "color",
      placeholder: "#151a24",
      defaultValue: CONFIG_DEFAULT.CUSTOM_THEME_CARD,
      dependsOn: "CUSTOM_THEME_ENABLED",
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_THEME_TEXT",
      label: "Text colour",
      desc: "Main text colour; secondary text is derived from it.",
      kind: "color",
      placeholder: "#e2e8f0",
      defaultValue: CONFIG_DEFAULT.CUSTOM_THEME_TEXT,
      dependsOn: "CUSTOM_THEME_ENABLED",
      grid: true,
      colSpan: 1,
    },
    { feature: "customize", label: "Background", kind: "divider" },
    {
      feature: "customize",
      key: "CUSTOM_PAGE_BG_URL",
      label: "Page background image",
      desc: "Image URL shown behind every Intra page (fixed, covers the window). Leave empty to disable.",
      kind: "url",
      placeholder: "https://…/wallpaper.jpg",
      defaultValue: CONFIG_DEFAULT.CUSTOM_PAGE_BG_URL,
      fullWidth: true,
    },
    {
      feature: "customize",
      key: "CUSTOM_PAGE_BG_PRESET",
      label: "Background preset",
      desc: "Built-in gradient behind every page, used when no image URL is set.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_PAGE_BG_PRESET,
      options: [
        { label: "None", value: "none" },
        { label: "Aurora", value: "aurora" },
        { label: "Sunset", value: "sunset" },
        { label: "Ocean", value: "ocean" },
        { label: "Forest", value: "forest" },
        { label: "Monochrome", value: "mono" },
        { label: "Midnight", value: "midnight" },
        { label: "Candy", value: "candy" },
        { label: "Lava", value: "lava" },
        { label: "Nord", value: "nord" },
        { label: "Dracula", value: "dracula" },
        { label: "42 teal", value: "teal" },
        { label: "Space", value: "space" },
        { label: "Mesh", value: "mesh" },
      ],
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_BG_ANIMATE",
      label: "Animate the gradient",
      desc: "Slow drift of the background preset. Off when your system asks for reduced motion.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CUSTOM_BG_ANIMATE,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_PAGE_BG_DIM",
      label: "Darken image (%)",
      desc: "Dark overlay on the background image to keep text readable. 0–90.",
      kind: "number",
      min: 0,
      max: 90,
      step: 5,
      defaultValue: CONFIG_DEFAULT.CUSTOM_PAGE_BG_DIM,
      dependsOn: "CUSTOM_PAGE_BG_URL",
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_CARD_OPACITY",
      label: "Card opacity (%)",
      desc: "Transparency of cards, with a subtle blur. 30–100.",
      kind: "number",
      min: 30,
      max: 100,
      step: 5,
      defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_OPACITY,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_CARD_STYLE",
      label: "Card style",
      desc: "Shadow and border of cards.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_STYLE,
      options: [
        { label: "Intra default", value: "default" },
        { label: "Flat", value: "flat" },
        { label: "Soft shadow", value: "soft" },
        { label: "Strong shadow", value: "strong" },
        { label: "Outlined (accent)", value: "outlined" },
        { label: "Glass", value: "glass" },
        { label: "Accent stripe", value: "stripe" },
      ],
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_SCROLLBAR",
      label: "Scrollbar",
      desc: "Style of the page scrollbars.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_SCROLLBAR,
      options: [
        { label: "Browser default", value: "default" },
        { label: "Thin", value: "thin" },
        { label: "Thin, accent colour", value: "accent" },
        { label: "Hidden", value: "hidden" },
      ],
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_AVATAR_SHAPE",
      label: "Avatar shape",
      desc: "Shape of the profile picture on profiles.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_AVATAR_SHAPE,
      options: [
        { label: "Circle", value: "circle" },
        { label: "Rounded square", value: "rounded" },
        { label: "Square", value: "square" },
      ],
      grid: true,
      colSpan: 1,
    },
    { feature: "customize", label: "Dashboard cards", kind: "divider" },
    {
      feature: "customize",
      key: "CUSTOM_CARD_BORDER_MODE",
      label: "Card border",
      desc: "Frame every dashboard card (Agenda, Evaluations, Achievements, Projects, Roulette, Logtime) like the Logtime widget.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_BORDER_MODE,
      options: [
        { label: "None", value: "none" },
        { label: "Accent colour", value: "accent" },
        { label: "Custom colour", value: "custom" },
      ],
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_CARD_BORDER_COLOR",
      label: "Border colour",
      desc: "Used when Card border is set to Custom colour.",
      kind: "color",
      placeholder: "#00babc",
      defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_BORDER_COLOR,
      dependsOn: "CUSTOM_CARD_BORDER_MODE",
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_CARD_BORDER_WIDTH",
      label: "Border width (px)",
      desc: "1–6 px, also for per-card borders below.",
      kind: "number",
      min: 1,
      max: 6,
      step: 1,
      defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_BORDER_WIDTH,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_CARD_GLOW",
      label: "Card glow",
      desc: "Soft halo around every card, in the border colour (or the accent).",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_GLOW,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_CARD_TITLE_MODE",
      label: "Card titles",
      desc: "Colour of the AGENDA, PROJECTS… headings.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_TITLE_MODE,
      options: [
        { label: "Intra default", value: "default" },
        { label: "Accent colour", value: "accent" },
        { label: "Custom colour", value: "custom" },
      ],
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_CARD_TITLE_COLOR",
      label: "Title colour",
      desc: "Used when Card titles is set to Custom colour.",
      kind: "color",
      placeholder: "#00babc",
      defaultValue: CONFIG_DEFAULT.CUSTOM_CARD_TITLE_COLOR,
      dependsOn: "CUSTOM_CARD_TITLE_MODE",
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      label: "Per-card colours",
      desc: "Give each card its own background, border and title colour, and a glow. Shared with your public look.",
      kind: "custom-cards",
      fullWidth: true,
    },
    { feature: "customize", label: "Layout", kind: "divider" },
    {
      feature: "customize",
      key: "CUSTOM_DENSITY",
      label: "Density",
      desc: "Spacing between and inside cards. Experimental: follows the Intra's own layout classes.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_DENSITY,
      options: [
        { label: "Intra default", value: "default" },
        { label: "Compact", value: "compact" },
        { label: "Comfortable", value: "comfortable" },
      ],
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_HIDE_FOOTER",
      label: "Hide the footer",
      desc: "Removes the page footer on every Intra page.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.CUSTOM_HIDE_FOOTER,
      grid: true,
      colSpan: 1,
    },
    { feature: "customize", label: "Typography", kind: "divider" },
    {
      feature: "customize",
      key: "CUSTOM_FONT",
      label: "Font",
      desc: "Font family used on every Intra page. System fonts only, nothing is downloaded.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_FONT,
      options: [
        { label: "Intra default", value: "default" },
        { label: "System UI", value: "system" },
        { label: "Humanist (Segoe / Helvetica)", value: "humanist" },
        { label: "Rounded", value: "rounded" },
        { label: "Serif", value: "serif" },
        { label: "Monospace", value: "mono" },
        { label: "Custom…", value: "custom" },
      ],
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_FONT_FAMILY",
      label: "Custom font family",
      desc: "CSS font-family value, e.g. 'Fira Sans', sans-serif. Used when Font is set to Custom.",
      kind: "text",
      placeholder: "'Fira Sans', sans-serif",
      defaultValue: CONFIG_DEFAULT.CUSTOM_FONT_FAMILY,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_FONT_SCALE",
      label: "Size (%)",
      desc: "Scales the whole interface: 90 for a denser layout, 110 for larger text. 70–140.",
      kind: "number",
      min: 70,
      max: 140,
      step: 5,
      defaultValue: CONFIG_DEFAULT.CUSTOM_FONT_SCALE,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "customize",
      key: "CUSTOM_RADIUS",
      label: "Corners",
      desc: "Roundness of cards, buttons and inputs.",
      kind: "select",
      defaultValue: CONFIG_DEFAULT.CUSTOM_RADIUS,
      options: [
        { label: "Intra default", value: "default" },
        { label: "Square", value: "none" },
        { label: "Slightly rounded", value: "small" },
        { label: "Rounded", value: "large" },
        { label: "Very rounded", value: "full" },
      ],
      grid: true,
      colSpan: 1,
    },
    { feature: "customize", label: "Custom CSS", kind: "divider" },
    {
      feature: "customize",
      key: "CUSTOM_CSS",
      label: "Custom CSS",
      desc: "Applied last on every Intra page, on top of the theme and the settings above. Reload the page to undo a broken rule.",
      kind: "textarea",
      placeholder: "/* example */\n.dash-main { gap: 2rem; }",
      defaultValue: CONFIG_DEFAULT.CUSTOM_CSS,
      fullWidth: true,
    },
  ],
  advanced: [
    {
      feature: "advanced",
      key: "ADVANCED_OPEN_LINKS_NEW_TAB",
      label: "Open links in new tab",
      desc: "External links from Better Intra open in a new tab instead of the current one.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.ADVANCED_OPEN_LINKS_NEW_TAB,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "advanced",
      key: "EASTER_EGGS_ENABLED",
      label: "Easter eggs",
      desc: "Eight small secrets are hidden in the Intra. The About tab counts the ones you found.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.EASTER_EGGS_ENABLED,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "advanced",
      key: "DISABLE_ANIMATIONS",
      label: "Disable animations",
      desc: "Removes transition effects across all Better Intra features.",
      kind: "toggle",
      defaultValue: CONFIG_DEFAULT.DISABLE_ANIMATIONS,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "advanced",
      label: "Auto-detected campus",
      desc: "Your campus, detected automatically via the 42 API.",
      kind: "campus-info",
      fullWidth: false,
      grid: true,
      colSpan: 1,
    },
    {
      feature: "advanced",
      label: "Backup & Restore",
      desc: "Export or import your Better Intra settings as a JSON file.",
      kind: "action",
      actionType: "backup",
      actionLabel: "Backup",
      grid: true,
      colSpan: 1,
    },
    {
      feature: "advanced",
      label: "Reload campus config",
      desc: "Clears the cached campus/cluster configuration and re-fetches it.",
      kind: "action",
      actionType: "reload-campus",
      actionLabel: "Reload",
      grid: true,
      colSpan: 1,
    },
    { feature: "advanced", label: "Reset", kind: "divider" },
    {
      feature: "advanced",
      label: "Reset all data",
      desc: "Clear all Better Intra settings and start fresh. This cannot be undone.",
      kind: "action",
      actionType: "reset",
      actionLabel: "Reset",
    },
  ],
};
